# Fichier à mettre sur srv-web01 dans /etc/apache2/sites-available/intra.isec.local.conf
<VirtualHost *:80>                                                                                                   
    ServerName intra.isec.local
    DocumentRoot /var/www/intra.isec.local
    ErrorLog ${APACHE_LOG_DIR}/intra_error.log
    CustomLog ${APACHE_LOG_DIR}/intra_access.log combined
</VirtualHost>

