//Fichier à mettre dans /etc/kea/kea-dhcp-ddns.conf
"DhcpDdns":
{
  "ip-address": "127.0.0.1",
  "port": 53001,
  "control-socket": {
      "socket-type": "unix",
      "socket-name": "/run/kea/kea-ddns-ctrl-socket"
  },

  // Fichier de clé
  <?include "/etc/kea/tsig-keys.json"?>

  // IP et infos du DNS et de la zone directe à mettre à jour
  "forward-ddns" : {
      "ddns-domains" : [
        ¦ {
        ¦      "name": "isec.local.",
        ¦      "key-name": "dhcp-ns",
        ¦      "dns-servers": [
        ¦       ¦  { "ip-address": "192.168.0.200" }
        ¦      ]
        ¦ }
      ]
  },

  // IP et infos du DNS et de la zone inverse à mettre à jour
  "reverse-ddns" : {
      "ddns-domains" : [
        ¦ {
        ¦      "name": "0.168.192.in-addr.arpa.",
        ¦      "key-name": "dhcp-ns",
        ¦      "dns-servers": [
        ¦       ¦  { "ip-address": "192.168.0.200" }
        ¦      ]
        ¦ }
      ]
  }

}
}
