// Fichier à mettre dans /etc/kea/kea-dhcp4.conf
{                                                                                                                    
"Dhcp4": {
    "interfaces-config": {
        "interfaces": [ "ens33" ]
    },
    "dhcp-ddns": {
        "enable-updates": true,
    },
    "ddns-qualifying-suffix": "isec.local",
    "ddns-override-client-update": true,
    "ddns-update-on-renew": true,
    "lease-database": {
        "type": "memfile",
        "persist": true,
        "name": "/var/lib/kea/kea-leases4.csv"
    },
    "valid-lifetime": 3600,
    "renew-timer": 1800,
    "rebind-timer": 3150,

    "subnet4": [
        {
        ¦   "id": 1,
        ¦   "subnet": "192.168.0.0/24",
        ¦   "pools": [ { "pool": "192.168.0.100 - 192.168.0.199" } ],
        ¦   "option-data": [
        ¦       { "name": "routers", "data": "192.168.0.254" },
        ¦       { "name": "domain-name-servers", "data": "192.168.0.200, 192.168.0.201" },
        ¦       { "name": "domain-name", "data": "isec.local" }
        ¦   ],
        ¦   "ddns-qualifying-suffix": "isec.local"
        }
    ],

}
}

